{
  config,
  lib,
  pkgs,
  username,
  ...
}: {
  # Age key location for decryption
  # This key is bootstrapped from Bitwarden on fresh installs
  age.identityPaths = [
    "/etc/ssh/ssh_host_ed25519_key"   # Host SSH key (auto-generated by NixOS)
    "/var/lib/age/key.txt"            # Master age key (from Bitwarden bootstrap)
  ];

  # Secret declarations — decrypted at system activation to /run/agenix/
  age.secrets = {
    # --- SSH ---
    ssh_pro_id_rsa = {
      file = ../../secrets/ssh/pro_id_rsa.age;
      owner = username;
      group = "users";
      mode = "0600";
      path = "/home/${username}/.ssh/pro_id_rsa";
    };
    ssh_pro_id_rsa_pub = {
      file = ../../secrets/ssh/pro_id_rsa.pub.age;
      owner = username;
      group = "users";
      mode = "0644";
      path = "/home/${username}/.ssh/pro_id_rsa.pub";
    };
    ssh_config = {
      file = ../../secrets/ssh/config.age;
      owner = username;
      group = "users";
      mode = "0600";
      path = "/home/${username}/.ssh/config";
    };

    # --- GPG ---
    gpg_personal_private = {
      file = ../../secrets/gpg/personal-private-key.asc.age;
      owner = username;
      group = "users";
      mode = "0600";
    };
    gpg_personal_public = {
      file = ../../secrets/gpg/personal-public-key.asc.age;
      owner = username;
      group = "users";
      mode = "0644";
    };
    gpg_trustdb = {
      file = ../../secrets/gpg/trustdb.gpg.age;
      owner = username;
      group = "users";
      mode = "0600";
    };
    gpg_private_keys = {
      file = ../../secrets/gpg/private-keys-v1.d.tar.age;
      owner = username;
      group = "users";
      mode = "0600";
    };

    # --- Git (shared) ---
    git_personal = {
      file = ../../secrets/git/personal.age;
      owner = username;
      group = "users";
      mode = "0600";
      path = "/home/${username}/.config/git/personal";
    };
  }

  # --- Git (per host) ---
  // (lib.optionalAttrs (builtins.pathExists ../../secrets/git/${config.networking.hostName}) (
    let host = config.networking.hostName; in
    (lib.optionalAttrs (builtins.pathExists ../../secrets/git/${host}/work.age) {
      git_work = {
        file = ../../secrets/git/${host}/work.age;
        owner = username;
        group = "users";
        mode = "0600";
        path = "/home/${username}/.config/git/work";
      };
    })
    // (lib.optionalAttrs (builtins.pathExists ../../secrets/git/${host}/conduktor.age) {
      git_conduktor = {
        file = ../../secrets/git/${host}/conduktor.age;
        owner = username;
        group = "users";
        mode = "0600";
        path = "/home/${username}/.config/git/conduktor";
      };
    })
  ))

  # --- Shell secrets (per host) ---
  // (let
    shellDir = ../../secrets/shell/${config.networking.hostName};
    shellFiles = if builtins.pathExists shellDir then builtins.attrNames (builtins.readDir shellDir) else [];
    ageFiles = builtins.filter (f: lib.hasSuffix ".age" f) shellFiles;
  in builtins.listToAttrs (map (f: let
    name = lib.removeSuffix ".age" f;
  in {
    name = "shell_${builtins.replaceStrings ["." "-"] ["_" "_"] name}";
    value = {
      file = ../../secrets/shell/${config.networking.hostName}/${f};
      owner = username;
      group = "users";
      mode = "0644";
      path = "/home/${username}/.bashrc.d/${name}";
    };
  }) ageFiles))

  # --- NetworkManager (per host) ---
  // (lib.optionalAttrs (builtins.pathExists ../../secrets/network/${config.networking.hostName}/connections.tar.age) {
    network_connections = {
      file = ../../secrets/network/${config.networking.hostName}/connections.tar.age;
      mode = "0600";
    };
  })

    # --- Bluetooth (per host) ---
  // (lib.optionalAttrs (builtins.pathExists ../../secrets/bluetooth/${config.networking.hostName}/devices.tar.age) {
    bluetooth_devices = {
      file = ../../secrets/bluetooth/${config.networking.hostName}/devices.tar.age;
      mode = "0600";
    };
  });

  # Restore GPG keyring from decrypted secrets
  system.activationScripts.restoreGpgKeys = lib.stringAfter [ "agenix" ] ''
    GPG_HOME="/home/${username}/.gnupg"
    mkdir -p "$GPG_HOME/private-keys-v1.d"
    chown ${username}:users "$GPG_HOME" "$GPG_HOME/private-keys-v1.d"
    chmod 700 "$GPG_HOME"

    # Import GPG keys
    if [ -f "${config.age.secrets.gpg_personal_private.path}" ]; then
      su - ${username} -c "${pkgs.gnupg}/bin/gpg --batch --import ${config.age.secrets.gpg_personal_private.path}" 2>/dev/null || true
    fi
    if [ -f "${config.age.secrets.gpg_personal_public.path}" ]; then
      su - ${username} -c "${pkgs.gnupg}/bin/gpg --batch --import ${config.age.secrets.gpg_personal_public.path}" 2>/dev/null || true
    fi

    # Restore trustdb
    if [ -f "${config.age.secrets.gpg_trustdb.path}" ]; then
      cp "${config.age.secrets.gpg_trustdb.path}" "$GPG_HOME/trustdb.gpg"
      chown ${username}:users "$GPG_HOME/trustdb.gpg"
      chmod 600 "$GPG_HOME/trustdb.gpg"
    fi

    # Restore private-keys-v1.d
    if [ -f "${config.age.secrets.gpg_private_keys.path}" ]; then
      ${pkgs.gnutar}/bin/tar xf "${config.age.secrets.gpg_private_keys.path}" -C "$GPG_HOME/private-keys-v1.d/" --strip-components=1 2>/dev/null || true
      chown -R ${username}:users "$GPG_HOME/private-keys-v1.d"
      chmod 700 "$GPG_HOME/private-keys-v1.d"
      chmod 600 "$GPG_HOME/private-keys-v1.d"/*.key 2>/dev/null || true
    fi
  '';

  # Restore NetworkManager connections
  system.activationScripts.restoreNetworkManager = lib.stringAfter [ "agenix" ] ''
    ${lib.optionalString (config.age.secrets ? network_connections) ''
    if [ -f "${config.age.secrets.network_connections.path}" ]; then
      ${pkgs.gnutar}/bin/tar xf "${config.age.secrets.network_connections.path}" -C /etc/NetworkManager/system-connections/ --strip-components=1 2>/dev/null || true
      chmod 600 /etc/NetworkManager/system-connections/*.nmconnection 2>/dev/null || true
    fi
    ''}
  '';

  # Restore Bluetooth pairings
  system.activationScripts.restoreBluetooth = lib.stringAfter [ "agenix" ] ''
    ${lib.optionalString (config.age.secrets ? bluetooth_devices) ''
    if [ -f "${config.age.secrets.bluetooth_devices.path}" ]; then
      ${pkgs.gnutar}/bin/tar xf "${config.age.secrets.bluetooth_devices.path}" -C /var/lib/bluetooth/ --strip-components=1 2>/dev/null || true
    fi
    ''}
  '';

  # Ensure agenix CLI is available for managing secrets
  environment.systemPackages = [ pkgs.age ];
}
