# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sr_mod" ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "iwlwifi" "ntsync" ];
  boot.extraModulePackages = [ ];

  # iGPU GTT memory ceiling for LLM inference (Radeon 890M has no dedicated VRAM; it borrows system RAM via GTT)
  # With BIOS set to "Auto", the GPU claims pages dynamically — memory not in use by the GPU stays available to the CPU.
  #
  # Formula: pages_limit = TARGET_GB × 262144
  #   1 page = 4 KiB → 1 GB = (1024 × 1024) KiB ÷ 4 = 262144 pages
  #   Example — 48 GB ceiling: 48 × 262144 = 12582912
  #
  # Tuning guidance (64 GB total RAM):
  #   Conservative  (safe headroom): 32 GB → 32 × 262144 =  8388608
  #   Balanced      (default below): 48 GB → 48 × 262144 = 12582912
  #   Aggressive  (leave 8 GB CPU):  56 GB → 56 × 262144 = 14680064
  boot.extraModprobeConfig = ''
    options ttm pages_limit=8388608
  '';

  # Get offset with : btrfs inspect-internal map-swapfile -r /swap/swapfile
  boot.kernelParams = ["resume_offset=533760"];
  boot.resumeDevice = "/dev/disk/by-label/nixos";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableAllFirmware = true;

  # nixos-hardware (framework-amd-ai-300-series) already sets:
  #   hardware.graphics.enable/enable32Bit, hardware.amdgpu.initrd.enable,
  #   hardware.cpu.amd.updateMicrocode, services.fprintd.enable, services.fwupd.enable,
  #   framework-tool package, amd_pstate=active, amdgpu.dcdebugmask kernel params.

  # OpenCL for compute workloads (llama.cpp ROCm backend, etc.) — not set by nixos-hardware module
  hardware.amdgpu.opencl.enable = true;

  hardware.i2c.enable = true; # for i2c-dev kernel module to enable ddcutils and edid hdr support

  # Bluetooth
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Experimental = true; # Show battery charge of Bluetooth devices
      };
    };
  };
  services.blueman.enable = true;

  powerManagement.enable = true;
  # nixos-hardware sets power-profiles-daemon to true by default; override to use auto-cpufreq instead
  services.power-profiles-daemon.enable = false;
  services.tlp.enable = false; # disable TLP to avoid conflicts with auto-cpufreq and for it's poor performance on AMD systems with amd_pstate=active via EPP
  programs.auto-cpufreq.enable = true;
  programs.auto-cpufreq.settings = {
    battery = {
      governor = "powersave";
      turbo = "never";
    };
    charger = {
      governor = "performance";
      turbo = "auto";
    };
  };

  # Framework-specific firmware update
  services.libinput.enable = true;
  services.touchegg.enable = true;

}
