# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, username, ... }:

let 
  uid = config.users.users.${username}.uid;
  primaryGroupName = config.users.users.${username}.group;
  gid = config.users.groups.${primaryGroupName}.gid;
in {
  imports = [
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" "ntsync" "wireguard" ];
  boot.kernelParams = [ "preempt=full"];
  boot.extraModulePackages = [ ];
  services.xserver.videoDrivers = [ "amdgpu" ];

  fileSystems."/" ={ 
    device = "/dev/disk/by-uuid/7a1db630-a289-42e3-a6e8-8d8ac9c00326";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/boot" ={ 
    device = "/dev/disk/by-uuid/062E-A48B";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  systemd.tmpfiles.rules = [
    # d <path> <mode> <uid> <gid> <age>
    "d /mnt/LinuxGames 0755 ${toString uid} ${toString gid} -"
  ];

  fileSystems."/mnt/LinuxGames" = {
    device = "/dev/disk/by-label/LinuxGames";
    fsType = "btrfs";
    options = [ "defaults" "nofail" ];
  };

  fileSystems."/mnt/WD1To" = {
    device = "/dev/disk/by-label/WD1To";
    fsType = "ntfs3";
    options = [ "defaults" "nofail" "windows_names" ];
  };

  swapDevices = [ ];

  # Make the mount visible to the desktop environment.
  services.udisks2.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # ROCm support
  hardware.amdgpu.opencl.enable = true;

  hardware.enableAllFirmware = true;
  services.fwupd.enable = true;

  hardware.i2c.enable = true; # for i2c-dev kernel module to enable ddcutils and edid  hdr support

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    # package = pkgs.unstable.mesa;
    # package32 = pkgs.unstable.pkgsi686Linux.mesa;
  };

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Experimental = true; # Show battery charge of Bluetooth devices
      };
    };
    input = {
      General = {
        IdleTimeout = 0;
      };
    };
  };
  services.blueman.enable = true;
  environment.systemPackages = with pkgs; [ 
    bluez-tools 
    mesa-demos
    lshw
  ];
  services.lact.enable = true; # AMDGPU controller GUI 

  # Enable SSD TRIM timer https://www.reddit.com/r/NixOS/comments/rbzhb1/if_you_have_a_ssd_dont_forget_to_enable_fstrim/
  services.fstrim.enable = true;
  
  services.tuned.enable = true;

  services.hardware.openrgb = { 
    enable = true;
    motherboard = "amd";
  };
}
